name: Kamidana Test
on:
  pull_request:

env:
  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
  SLACK_API_ERROR_RAISE: true

jobs:
  kamidana-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: pip install
        run: python -m pip install --upgrade pip setuptools wheel
      - name: setup
        run: python setup.py install

      - name: kamidana
        id: kamidana
        uses: srz-zumix/kamidana-action@v2
        with:
          template: sample/profile.j2
          output_file: test.txt
          tee: true
          additonals: |
            yurumikuji.yurumikuji
      - run: |
          cat << 'EOS' | tee output.txt
          ${{ steps.kamidana.outputs.text }}
          EOS
          diff output.txt test.txt
