name: Kamidana Test
on:
  pull_request:

permissions: {}

jobs:
  kamidana-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_API_ERROR_RAISE: true
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: '3.13'
      - name: setup
        run: pip install .

      - name: kamidana
        id: kamidana
        uses: srz-zumix/kamidana-action@a6bb4009c385c154ac0ec04b988cf3f7c785c438 # v3.0.0
        with:
          template: sample/profile.j2
          output_file: test.txt
          tee: true
          additonals: |
            yurumikuji.yurumikuji
      - run: |
          cat << 'EOS' | tee output.txt
          ${{ steps.kamidana.outputs.text }}
          EOS
          diff output.txt test.txt
